# Classifying Iris Species

### Challenge

In this section we will create a simple machine learning application for classify iris flowers.  
We have a collection of measurements associated with iris flowwers: the length and width of the petals and length and width of the sepals, in centimeters.  
There are three classes available: setosa, versicolor and virginica.

**Because we have measurements for which we know the correct species of iris, this is a supervised learning problem. In this problem we want to predict one of several options. This is a classification problem.** The possible outputs are called *classes*; the known class for particular data point is called *label*.

### Importing the data

In [1]:
# import data
from sklearn.datasets import load_iris
iris_dataset = load_iris()

### Visualise the dataset

In [2]:
type(iris_dataset)

sklearn.utils.Bunch

In [3]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [4]:
print(iris_dataset['DESCR'] + "\n")

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [5]:
# value of target names
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [6]:
# value of feature names
print("Feature names: {}".format(iris_dataset['feature_names']))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
# data is stored in a numpy array
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [8]:
iris_dataset['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Each row corresponds to one flower, columns are values of the features. Each flower is called sample in machine learning terms; ist characteristics are called features.

In [9]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [10]:
print("First five rows of data: \n {}".format(iris_dataset['data'][:5]))

First five rows of data: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
print("Shape of labels: {}".format(iris_dataset['target'].shape))

Shape of labels: (150,)


In [12]:
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

The meanings of these numbers are given by the iris_dataset['target_names'] array: 0 means 'setosa', 1 means 'versicolor' and 2 means 'virginica'.

### Training and Testing Data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=17)

In [15]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)


In [16]:
print("X_train shape: {}".format(X_test.shape))
print("y_train shape: {}".format(y_test.shape))

X_train shape: (38, 4)
y_train shape: (38,)


Transform the data array in a pandas Data Frame and plot a pair plot using the pandas scatter matrix function.

In [17]:
import pandas as pd

In [18]:
# create dataframe from data in X_train
# label the columns using the strigs in iris_dataset.feature_names
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
iris_dataframe

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  6.1               2.8                4.0               1.3
1                  4.9               3.1                1.5               0.1
2                  5.7               3.0                4.2               1.2
3                  6.6               3.0                4.4               1.4
4                  5.3               3.7                1.5               0.2
5                  5.8               2.7                4.1               1.0
6                  6.8               3.0                5.5               2.1
7                  5.5               2.5                4.0               1.3
8                  5.9               3.2                4.8               1.8
9                  5.8               2.7                5.1               1.9
10                 6.7               3.1                4.7               1.5
11                 5.1               3.3                1.7               0.5
12                 6.2               3.4                5.4               2.3
13                 6.6               2.9                4.6               1.3
14                 5.8               2.7                3.9               1.2
15                 6.7               3.0                5.0               1.7
16                 5.6               2.7                4.2               1.3
17                 4.4               3.2                1.3               0.2
18                 6.9               3.1                4.9               1.5
19                 5.8               2.7                5.1               1.9
20                 6.5               3.0                5.8               2.2
21                 5.0               3.5                1.3               0.3
22                 5.0               3.6                1.4               0.2
23                 7.4               2.8                6.1               1.9
24                 4.9               3.0                1.4               0.2
25                 6.0               2.2                5.0               1.5
26                 6.7               2.5                5.8               1.8
27                 5.7               3.8                1.7               0.3
28                 6.4               3.1                5.5               1.8
29                 4.8               3.4                1.9               0.2
..                 ...               ...                ...               ...
82                 6.0               2.7                5.1               1.6
83                 4.9               2.5                4.5               1.7
84                 5.2               3.5                1.5               0.2
85                 6.3               3.3                4.7               1.6
86                 4.3               3.0                1.1               0.1
87                 5.6               2.8                4.9               2.0
88                 6.5               2.8                4.6               1.5
89                 5.1               3.8                1.9               0.4
90                 4.7               3.2                1.3               0.2
91                 5.9               3.0                4.2               1.5
92                 5.2               4.1                1.5               0.1
93                 6.9               3.1                5.4               2.1
94                 4.8               3.1                1.6               0.2
95                 6.0               3.0                4.8               1.8
96                 4.6               3.4                1.4               0.3
97                 6.1               2.9                4.7               1.4
98                 7.9               3.8                6.4               2.0
99                 5.4               3.7                1.5               0.2
100                4.5               2.3                1.3               0.3
101                5.1     

In [19]:
# create a scatter matrix from the dataframe, color by y_train
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(20, 20), marker='o',
                        hist_kwds={'bins': 20}, s=60, alpha=0.8, cmap=mglearn.cm3)

NameError: name 'mglearn' is not defined